@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMzZmMjhiOC02MGNhLTQ3MmQtYjM1MS0wNjE1YTQ0OTZmMmEiLCJpYXQiOjE3OTEzNDUzMjcsImV4cCI6MTc5MTM0ODkyN30.Aqsf5gK2yTZP7M8a8zbcp0QQlFxVfZwhqMfdd4Ur01g

### Get user cart
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json



