@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMzZmMjhiOC02MGNhLTQ3MmQtYjM1MS0wNjE1YTQ0OTZmMmEiLCJpYXQiOjE3OTE2MTA4NjMsImV4cCI6MTc5MTYxNDQ2M30.fBzMQjWEg6pXk4CyNRfFIGC_L2zRNtw5eGVSKFbxJVI 

### ADD ITEM TO CART
POST {{baseUrl}}/cart-items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": "4ab5df51-23df-4467-b99d-c65a8d2d2ba9"
}


