@baseUrl = http://localhost:3000
@productId = 2516ab02-c3fb-4b0e-a4d1-9cb0cf77898a

###Get all products
GET {{baseUrl}}/products

###Create product    
POST {{baseUrl}}/products
Content-Type: application/json

{
    "title":"my product",
    "description":"my product description",
    "price": 100
}

###Update product
PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
    "title":"updated ",
    "description":"updated",
    "price": 150
}

###Delete product
DELETE {{baseUrl}}/products/{{productId}}

###Login 
POST {{baseUrl}}/auth/login

{
    "username":"john.doe@example.com",
    "password":"password123"
}

