@baseUrl = http://localhost:3000
@productId = 52cc5a55-64ac-4bb2-98e1-20f0591394b5
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMzZmMjhiOC02MGNhLTQ3MmQtYjM1MS0wNjE1YTQ0OTZmMmEiLCJpYXQiOjE3ODkyNTEzMDQsImV4cCI6MTc4OTI1NDkwNH0.DzbiinfdshBSzJ99yC2CoZfQLn7JfLhJZPJUmGDKNy8
###Get all products
GET {{baseUrl}}/products

###Get product by id
GET {{baseUrl}}/products/{{productId}}

###Create product    
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"my product",
    "description":"my product description",
    "price": 100
}

###Update product
PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
    "title":"updated ",
    "description":"updated",
    "price": 150
}

###Delete product
DELETE {{baseUrl}}/products/{{productId}}

###Get all products user 
GET {{baseUrl}}/products/my-products
Authorization: Bearer {{token}}

